//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsientosContables
    {
        public int Id_AsientoContable { get; set; }
        public Nullable<int> Id_Cliente { get; set; }
        public string Descripcion { get; set; }
        public int Cuenta { get; set; }
        public string TipoMovimiento { get; set; }
        public System.DateTime FechaAsiento { get; set; }
        public int MontoAsiento { get; set; }
        public string Estado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Clientes Clientes1 { get; set; }
    }
}
