//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.AsientosContables = new HashSet<AsientosContables>();
            this.AsientosContables1 = new HashSet<AsientosContables>();
            this.Facturacion = new HashSet<Facturacion>();
            this.Facturacion1 = new HashSet<Facturacion>();
        }
    
        public int Id_Cliente { get; set; }
        [DisplayName("Nombre comercial")]
        public string nombreComercial { get; set; }
        public string RNC { get; set; }
        [DisplayName("Cuenta contable")]
        public int cuentaContable { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsientosContables> AsientosContables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsientosContables> AsientosContables1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturacion> Facturacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturacion> Facturacion1 { get; set; }
    }
}
