//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentasContables
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentasContables()
        {
            this.AsientosContables = new HashSet<AsientosContables>();
            this.Clientes = new HashSet<Clientes>();
            this.CuentasContables1 = new HashSet<CuentasContables>();
        }
    
        public int ID_CuentaContable { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> PermiteMov { get; set; }
        public Nullable<byte> Tipo { get; set; }
        public Nullable<byte> Nivel { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> Id_CuentaMayor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsientosContables> AsientosContables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clientes> Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentasContables> CuentasContables1 { get; set; }
        public virtual CuentasContables CuentasContables2 { get; set; }
    }
}
