//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AsientosContables
    {
        public Nullable<int> Id_Articulo { get; set; }
        public string Comentario { get; set; }
        public int Id_Cliente { get; set; }
        public int ID_CuentaContable { get; set; }
        public string tipo_movimiento { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal PrecioUnitario { get; set; }
        public string Estado { get; set; }
    }
}
